# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Goce's Codes
tagline:          'Just some tech stuff'
description:      ''
url:              https://gocedoko.github.io
baseurl:          /

author:
  name:           'Goce Dokoski'
  url:            https://gocedoko.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
